name: Building GSI..

on: [push]

env:
  ROM_URL: https://mirror.rahul137.workers.dev/PixelPlusUI_3.6_RMX2185-11.0-20210617-1608-OFFICIAL.zip
  ROM_NAME: Generic:PPUI-3.6
  ZIP_NAME: PPUI-3.6-20210618-RK137GSI.img
  TZ: Asia/Kolkata
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean
           sudo apt install expect -y
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget expect

       
       - name: Clone ErfanGSIs
         run: git clone --recurse-submodules https://github.com/rahulkhatri137/Erfan ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: XZip AB and upload 
         run: |
              sudo chmod -R 777 ErfanGSIs/output
              cd ErfanGSIs/output
              ls
              sudo chmod -R 777 *.img
              rm -rf *txt
              ls
              xz -cfev9 * > $ZIP_NAME.xz
              ls
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put *.xz\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
