name: Building GSI..

on: [push]

env:
  ROM_URL: https://mirror.rahul137.workers.dev/Havoc-OS-v4.6-20210620-CPH1859-Unofficial.zip
  ROM_NAME: Generic:Havoc
  ZIP_NAME: Havoctest-RK137GSI.img
  TZ: Asia/Kolkata
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget expect

       
       - name: Clone ErfanGSIs
         run: git clone --recurse-submodules https://github.com/rahulkhatri137/Erfan ErfanGSIs
       
       - name: Setup
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Rom & Generate GSI
         run: sudo ./ErfanGSIs/img.sh $ROM_URL $ROM_NAME
       
       - name: XZip
         run: |
              sudo ./ErfanGSIs/reimg.sh
              cd output
              ls

       - name: Upload 
         run: |
              cd ErfanGSIs/output/final
              ls
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put *.xz\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
